#!/bin/bash
grep -i "root" /etc/passwd#!/bin/bash
grep -i "root" /etc/passwd#!/bin/bash
grep -i "root" /etc/passwd#!/bin/bash
grep -i "root" /etc/passwd#!/bin/bash
grep -i "root" /etc/passwd#!/bin/bash
grep -i "root" /etc/passwd#!/bin/bash
grep -i "root" /etc/passwd#!/bin/bash
grep -i "root" /etc/passwd
